version: '3.8'
services:
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
  user-service:
    build: ./services/user-service
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
  market-data:
    build: ./services/market-data
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
